[package]
name = "pulse"
version = "0.3.4"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]
license = "Apache-2.0"
description = "A library for async wake signals"
homepage = "https://github.com/csherratt/pulse"

[dependencies]
atom = "*"
time = "*"

[features]
default = []
callback = []
